% Patterns_get_smooth_profiles_Tact 

Post_stim_Calc_Spikerate_profile_1ms_bin =    GLOBAL_const.Post_stim_Calc_Spikerate_profile_1ms_bin ;
 
    [  Patterns.TimeBin_Total_Spikes_1ms , Patterns.TimeBin_Total_Spikes_std_1ms , Patterns.Spike_Rate_Patterns_1ms  , ...
        Patterns.Spike_Rate_Signature_1ms ,  Patterns.Spike_Rate_Signature_std_1ms ,  Patterns.Spike_Rate_1ms_smooth_Max_corr_delay , ...
        Patterns.Spike_Rate_Signature_1ms_smooth ,Patterns.Amp_Patterns_1ms , Patterns.Amps_Signature_1ms  , Patterns.Amps_Signature_1ms_std , Patterns.Amps_Signature_1ms_smooth , ...
        Patterns.Spike_Rate_1ms_Max_corr_delay , Patterns.Spike_Rate_Signature_1ms_interp , Patterns.DT_bin_interp ] = ... 
             SR_profile_1ms_calc( Post_stim_Calc_Spikerate_profile_1ms_bin ,  N , Nb ,Patterns.bursts  , Patterns.bursts_amps  , Global_flags.Search_Params ) ;
       
         
  %>>>>>>>>>>
  Post_stim_interval_end  = Patterns.Poststim_interval_END ;
  Post_stim_interval_start = Patterns.Poststim_interval_START ;
           fire_bins = floor( ( Post_stim_interval_end -  Post_stim_interval_start)  / DT_step ) ;
            times_fire_bins =DT_step * ( 1 : fire_bins );
      
        %--- Burst activation based on average activity ---------------   
         
        DT_bin_1ms = 1 ;
        [ Patterns.burst_activation_2_mean , Patterns.burst_activation_2 , Patterns.burst_activation_3_smooth_1ms_mean , ...
     Patterns.burst_max_rate_delay_ms , Patterns.burst_max_rate_delay_ms_mean    ] = ... 
            SR_profile_Tact2_3_from_1msProfile( N , Nb , Post_stim_Calc_Spikerate_profile_1ms_bin ...
            , GLOBAL_const.Post_stim_activation_based_smooth_find_all_bursts , ...
             (Post_stim_interval_end - Post_stim_interval_start )  ,  DT_bin_1ms , Patterns.Spike_Rate_Patterns_1ms , ...
             GLOBAL_const , Global_flags.Stim_Search_Params.T_activation_stat_threshold_param ,...
             Global_flags , Patterns.Spike_Rate_Signature_1ms_smooth , Patterns.burst_activation_mean , Patterns.Spike_Rates_each_channel_mean ) ;       
         